# Generated by Django 3.2 on 2021-05-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('countryname', models.CharField(max_length=100)),
                ('countrycode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('population', models.IntegerField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
