# Generated by Django 3.2 on 2021-05-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countries',
            table='countries',
        ),
    ]
