# Generated by Django 3.2 on 2021-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globe', '0002_alter_countries_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('Anime', models.CharField(max_length=100)),
                ('Animejap', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Desciption', models.TextField()),
                ('Ratings', models.IntegerField()),
            ],
            options={
                'db_table': 'anime',
            },
        ),
        migrations.DeleteModel(
            name='countries',
        ),
    ]
